//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIM()
        {
            this.CHITIETSUDUNGs = new HashSet<CHITIETSUDUNG>();
            this.HOADONTINHCUOCs = new HashSet<HOADONTINHCUOC>();
        }
    
        public string id_Sim { get; set; }
        public string CMND { get; set; }
        public System.DateTime NgayKichHoat { get; set; }
        public string TrangThaiSIM { get; set; }
        public Nullable<System.DateTime> Ngay_lock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSUDUNG> CHITIETSUDUNGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONTINHCUOC> HOADONTINHCUOCs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
